@echo off
setlocal EnableExtensions EnableDelayedExpansion

title EventZen - One Click Start

echo ============================================
echo   EventZen - Startup Script
echo ============================================
echo.

set "SCRIPT_DIR=%~dp0"
set "APP_DIR=%SCRIPT_DIR%eventzen"

if not exist "%APP_DIR%\docker-compose.yml" (
  set "APP_DIR=%SCRIPT_DIR%"
)

if not exist "%APP_DIR%\docker-compose.yml" (
  echo [ERROR] Could not find docker-compose.yml.
  echo Place this script in repository root or run it from that location.
  exit /b 1
)

echo [1/6] Checking Docker CLI...
where docker >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Docker CLI is not installed or not in PATH.
  echo Install Docker Desktop and try again.
  exit /b 1
)

echo [2/6] Checking Docker engine...
docker info >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Docker engine is not running.
  echo Start Docker Desktop, wait until it is ready, then rerun this script.
  exit /b 1
)

echo [3/6] Checking Docker Compose...
docker compose version >nul 2>&1
if errorlevel 1 (
  echo [ERROR] Docker Compose V2 is not available.
  echo Update Docker Desktop and ensure 'docker compose' works.
  exit /b 1
)

set "ENV_FILE=%APP_DIR%\.env"
if not exist "%ENV_FILE%" (
  echo [4/6] .env not found. Creating a local development .env ...
  > "%ENV_FILE%" (
    echo # Auto-generated by EventZenStart.bat
    echo # Edit these values if needed.
    echo.
    echo MYSQL_ROOT_PASSWORD=eventzen_root_123
    echo AUTH_DB_PASSWORD=eventzen_auth_123
    echo EVENT_DB_PASSWORD=eventzen_event_123
    echo FINANCE_DB_PASSWORD=eventzen_fin_123
    echo.
    echo MONGO_ROOT_PASSWORD=eventzen_mongo_123
    echo REDIS_PASSWORD=eventzen_redis_123
    echo.
    echo JWT_SECRET=eventzen_jwt_secret_very_long_value_123456
    echo JWT_REFRESH_SECRET=eventzen_refresh_secret_very_long_value_123456
    echo TICKET_HMAC_SECRET=eventzen_ticket_hmac_secret_123456
    echo PII_ENCRYPTION_KEY=eventzen_pii_key_1234567890123456
    echo.
    echo KAFKA_BROKERS=kafka:29092
    echo.
    echo STRIPE_SECRET_KEY=sk_test_placeholder
    echo STRIPE_WEBHOOK_SECRET=whsec_placeholder
    echo SENDGRID_API_KEY=SG.placeholder
    echo TWILIO_SID=ACplaceholder
    echo TWILIO_AUTH_TOKEN=placeholder
    echo TWILIO_PHONE=+10000000000
    echo FCM_PROJECT_ID=placeholder
    echo FCM_PRIVATE_KEY=placeholder
    echo FCM_CLIENT_EMAIL=placeholder@example.com
    echo.
    echo BASE_URL=http://localhost:5174
    echo CORS_ORIGINS=http://localhost:5174,http://localhost:3000
    echo.
    echo HOST_FRONTEND_PORT=5174
    echo HOST_KONG_PROXY_PORT=8081
    echo HOST_KONG_SSL_PORT=8444
    echo HOST_AUTH_SERVICE_PORT=8093
    echo HOST_EVENT_SERVICE_PORT=8094
    echo HOST_VENUE_VENDOR_SERVICE_PORT=8095
    echo HOST_TICKETING_SERVICE_PORT=8096
    echo HOST_FINANCE_SERVICE_PORT=8097
    echo HOST_NOTIFICATION_SERVICE_PORT=8098
    echo HOST_MYSQL_AUTH_PORT=3310
    echo HOST_MYSQL_EVENTS_PORT=3311
    echo HOST_MYSQL_FINANCE_PORT=3312
    echo HOST_MONGO_VENUE_PORT=27021
    echo HOST_MONGO_TICKETING_PORT=27022
    echo HOST_MONGO_NOTIFICATION_PORT=27023
    echo HOST_REDIS_PORT=6381
    echo HOST_ZOOKEEPER_PORT=2183
    echo HOST_KAFKA_PORT=9094
    echo HOST_MINIO_API_PORT=9002
    echo HOST_MINIO_CONSOLE_PORT=9003
    echo HOST_ELASTICSEARCH_PORT=9201
    echo HOST_VAULT_PORT=8200
    echo HOST_PROMETHEUS_PORT=9090
    echo HOST_GRAFANA_PORT=3001
    echo.
    echo VAULT_MODE=dev
    echo VAULT_ADDR=http://127.0.0.1:8200
    echo VAULT_TOKEN=eventzen-dev-root
    echo VAULT_NAMESPACE=
    echo VAULT_KV_MOUNT=secret
    echo VAULT_SECRET_PREFIX=eventzen
    echo VAULT_DEV_ROOT_TOKEN=eventzen-dev-root
    echo VAULT_SKIP_VERIFY=true
    echo.
    echo MINIO_ROOT_USER=eventzen
    echo MINIO_ROOT_PASSWORD=eventzen123
    echo MINIO_ACCESS_KEY=eventzen
    echo MINIO_SECRET_KEY=eventzen123
  )
) else (
  echo [4/6] Using existing .env
)

echo [5/6] Starting EventZen services with Docker Compose...
pushd "%APP_DIR%"
docker compose up -d --build
if errorlevel 1 (
  echo [ERROR] Docker Compose startup failed.
  popd
  exit /b 1
)

echo [6/6] Startup complete. Current service status:
docker compose ps
popd

echo.
echo ============================================
echo   EventZen is running
echo ============================================
echo Frontend           : http://127.0.0.1:5174
echo API Gateway        : http://127.0.0.1:8081
echo Swagger Index      : http://127.0.0.1:8081/api/v1/docs
echo Prometheus         : http://127.0.0.1:9090
echo Grafana            : http://127.0.0.1:3001
echo MinIO Console      : http://127.0.0.1:9003
echo.
echo To stop everything:
echo   cd /d "%APP_DIR%"
echo   docker compose down
echo ============================================

endlocal
exit /b 0
